//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSC2017_Paper1_29_10_2020
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int id { get; set; }
        public int userIdFK { get; set; }
        public System.DateTime loginTime { get; set; }
        public Nullable<System.DateTime> logoutTime { get; set; }
        public string failureShortReason { get; set; }
        public string failureLongReason { get; set; }
    
        public virtual User User { get; set; }
    }
}
