//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbuDhabu_Session4_12_11_2020
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerTable
    {
        public int answerId { get; set; }
        public Nullable<System.DateTime> dateOfAnswer { get; set; }
        public string depature { get; set; }
        public string arrival { get; set; }
        public string gender { get; set; }
        public Nullable<int> cabinTypeIdFK { get; set; }
        public Nullable<int> q1RatingFK { get; set; }
        public Nullable<int> q2RatingFK { get; set; }
        public Nullable<int> q3RatingFK { get; set; }
        public Nullable<int> q4RatingFK { get; set; }
        public Nullable<int> age { get; set; }
    
        public virtual CabinType CabinType { get; set; }
        public virtual RatingTable RatingTable { get; set; }
        public virtual RatingTable RatingTable1 { get; set; }
        public virtual RatingTable RatingTable2 { get; set; }
        public virtual RatingTable RatingTable3 { get; set; }
    }
}
