//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covid19API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactTracing
    {
        public long ID { get; set; }
        public Nullable<long> FTE_ID { get; set; }
        public long LocationID { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
        public decimal Temp { get; set; }
        public System.DateTime RegisterDateTime { get; set; }
        public Nullable<System.DateTime> ExitDateTime { get; set; }
    
        public virtual FTE FTE { get; set; }
        public virtual Location Location { get; set; }
    }
}
